### ISSUE TITLE
Change BorderLayout to GridBagLayout

### ISSUE THREAD

**Issue by mrafsyam** [iserifith/ScoreBoard#1]
See https://www.tutorialspoint.com/swing/swing_gridbaglayout.htm

Use both
GridBagLayout layout = new GridBagLayout();
GridBagConstraints gbc = new GridBagConstraints();

Note that GridBagLayout is applicable to BOTH JFRAME and JPANEL

**Comment by iserifith** [comment]
![screenshot from 2016-07-28 07 38 30](https://cloud.githubusercontent.com/assets/21057925/18688353/96475fd6-7fb6-11e6-9d4b-74c448904b46.png)

**Comment by iserifith** [comment]
![screenshot from 2016-09-21 04 45 52](https://cloud.githubusercontent.com/assets/21057925/18688371/b46560ee-7fb6-11e6-87bc-e7f9ba3bceac.png)

**Comment by mrafsyam** [comment]
Done
