### ISSUE TITLE
Set size of JTextField accordingly

### ISSUE THREAD

**Issue by mrafsyam** [iserifith/ScoreBoard#2]
Play around with

JTextField titleText = new JTextField( "title" );
titleText.setPreferredSize( new Dimension( 200, 24 ) );

See Dimension : http://docs.oracle.com/javase/6/docs/api/java/awt/Dimension.html

**Comment by iserifith** [comment]
![screenshot from 2016-09-21 15 11 04](https://cloud.githubusercontent.com/assets/21057925/18701187/f0daf4d8-800d-11e6-9a3c-61e5ad009eae.png)

**Comment by mrafsyam** [comment]
@iserifith do this change (set all font size accordingly), then attach screenshot here.

**Comment by mrafsyam** [comment]
Implemented. Good enough. Will enhance through other issue later.
