### ISSUE TITLE
Change the numbers' font to "digital" type

### ISSUE THREAD

**Issue by mrafsyam** [iserifith/ScoreBoard#3]
Refer here : http://stackoverflow.com/questions/17378625/how-to-set-digital-clock-font-in-jlabel

Download font file, place it project folder.

Basically all numbers must have font type digital

![screenshot from 2016-09-21 03-11-29](https://cloud.githubusercontent.com/assets/6120781/18685113/5184d430-7fa9-11e6-9036-0788e4613570.png)

**Comment by mrafsyam** [comment]
![screenshot from 2016-09-22 00-59-31](https://cloud.githubusercontent.com/assets/6120781/18720752/e31a59ea-805f-11e6-8116-5e01baf5fcf1.png)

@iserifith Learn how to apply font. Apply it to the respective textfield. After done, attach a screenshot here.

**Comment by iserifith** [comment]
![screenshot from 2016-09-22 16 19 18](https://cloud.githubusercontent.com/assets/21057925/18741253/a9b9dad2-80e0-11e6-9a15-b11fcf16088b.png)
