### ISSUE TITLE
Add timer and some labels to show clock/counter

### ISSUE THREAD

**Issue by mrafsyam** [iserifith/ScoreBoard#6]
There should be 2 labels to show clock
1. Game clock - this is (the bigger clock) limited from 00:00 (0 minutes and 0 second) to 12:00 (12 minutes)
2. Shot clock - this is (the smaller clock) limited from 00 (0 seconds) to 24 (24 seconds)

Note : The value is incremented by the second using the timer.

![main](https://cloud.githubusercontent.com/assets/6120781/18735630/df6e0312-80b1-11e6-97fa-8e394fd3b3c8.gif)

**Comment by mrafsyam** [comment]
Code for a second, left here for reference 

```
package scoreBoard;

import java.util.Timer;
import java.util.TimerTask;

public class TimerDemo {

   public static void main(String[] args) {

      // instantiate our TimerTask "extended" class 
      RunEverySecond tasknew = new RunEverySecond();

      // instantiate a Timer object
      Timer timer = new Timer();

      // scheduling the task at fixed rate delay. See http://docs.oracle.com/javase/7/docs/api/java/util/Timer.html#scheduleAtFixedRate(java.util.TimerTask,%20long,%20long)
      timer.scheduleAtFixedRate(tasknew,0,1000);      
   } 
}

/*
* TimerTask is an "Abstract" class - cannot be instantiated but can only be extended
* see https://docs.oracle.com/javase/7/docs/api/java/util/TimerTask.html#TimerTask()
*/
class RunEverySecond extends TimerTask {

   public void run() {

      // call the method to change the value of label for timer/clock here
      System.out.println("Beep! One second");
   }
}
```

**Comment by mrafsyam** [comment]
Game Clock from `00 : 00` to `12 : 00`

Lets say the first `00` is textfieldA and the second `00` is textfieldB
So, essentially `[textfieldA] : [textfieldB]`

```
method countEverySecond() {
    get value from textfieldB, lets assign this in variable valueB
    increment valueB by 1

    if valueB > 60 {

        get valuefrom textfieldA, lets assign this in variable valueA
        increment valueA by 1

        if valueA > 12 {
            stop timer
        }

    }
}
```

**Comment by iserifith** [comment]
![screenshot from 2016-09-26 00 01 14](https://cloud.githubusercontent.com/assets/21057925/18816441/b1e9361e-837c-11e6-955f-0d3436b09539.png)

**Comment by mrafsyam** [comment]
@iserifith  Closed as the basic goals are achieved. 

Continue to the next issue
