### ISSUE TITLE
Change background, number colors

### ISSUE THREAD

**Issue by mrafsyam** [iserifith/ScoreBoard#8]
Can you make these changes 
1. the main background to Color.gray
2. All counter background to Color.black
3. Clock number to Color.red
4. Scores to Color.yellow
5. Period to Color.green

Similar to these : 
![screenshot from 2016-09-21 03-11-29](https://cloud.githubusercontent.com/assets/6120781/18685113/5184d430-7fa9-11e6-9036-0788e4613570.png)

**Comment by iserifith** [comment]
![screenshot from 2016-09-23 12 53 33](https://cloud.githubusercontent.com/assets/21057925/18774564/13e165d6-818d-11e6-8b86-fa4cc298638e.png)

**Comment by mrafsyam** [comment]
Ok, closing this one. Proceed to next issue.
